# Generated by Django 5.0 on 2024-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=130)),
                ('password', models.CharField(max_length=130)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
