# Generated by Django 4.1 on 2024-01-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_planner_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "productType",
                    models.CharField(
                        choices=[
                            ("PH", "Photography"),
                            ("CA", "Catering"),
                            ("DE", "Decoration"),
                            ("MU", "Music"),
                        ],
                        default="PH",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
