# Generated by Django 5.0 on 2024-01-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('orderStatus', models.CharField(max_length=200)),
                ('RequestedPackages', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
