# Generated by Django 4.2.8 on 2024-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
