# Generated by Django 5.0 on 2024-01-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_api', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
