# Generated by Django 4.1 on 2024-01-25 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event_planner_api", "0003_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="event_planner_api.product",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="event_planner_api.customer",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="orders",
                        to="event_planner_api.product",
                    ),
                ),
            ],
        ),
    ]
