# Generated by Django 4.1 on 2024-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_planner_api", "0004_alter_service_product_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="order",
            old_name="id",
            new_name="orderID",
        ),
        migrations.AddField(
            model_name="order",
            name="orderDate",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="orderStatus",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
