# Generated by Django 4.1 on 2024-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "event_planner_api",
            "0005_message_rename_id_order_orderid_order_orderdate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
