# Generated by Django 5.0 on 2024-01-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner_api', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
