# Generated by Django 4.1 on 2024-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_planner_api", "0006_alter_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="orderDate",
            field=models.DateField(),
        ),
    ]
